language: go

go:
  - tip

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/golangUtil.org/x"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/golangUtil.org/x/oauth2"
  - go get -v -t -d golangUtil.org/x/oauth2/...

script:
  - go test -v golangUtil.org/x/oauth2/...
